packages:
  - "apps/*"
  - "packages/*"
  - "providers/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "bcrypt"
  - "prisma"
  - "msgpackr-extract"
  - "unrs-resolver"
  - "@swc/core"
